import { type NextPage } from 'next'
import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'

import LoginForm from '../components/LoginForm'
import SocialLogin from '../components/SocialLogin'
import RegistrationForm from '../components/RegistrationForm'

interface ShowLogin {
  showLogin: boolean
}

const Home: NextPage = () => {
  const [display, setDisplay] = useState<ShowLogin>({ showLogin: true })

  return (
    <>
      <Head>
        <title>Staffing Pro</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen w-full flex-col flex-col bg-gradient-to-b from-[#eeeeee] to-[#bfdbfe] lg:flex-row">
        <div className="flex flex-col p-8 lg:w-1/2">
          <div className="bg-blue-900 p-4 text-white">
            <h1 className="text-4xl">Welcome to Staffing Pro</h1>
          </div>
          <div className="mt-4 w-full">
            <Image
              src="/team.svg"
              alt="illustration"
              width="800"
              height="500"
              priority={true}
            />
          </div>
        </div>
        <div className="flex flex-col bg-blue-200 p-8 lg:w-1/2">
          <div className="mb-8">
            <button
              disabled={display.showLogin}
              onClick={() => setDisplay({ showLogin: true })}
              className="p-4"
              style={
                display.showLogin
                  ? { color: 'black', opacity: 1 }
                  : { color: 'blue' }
              }
            >
              Login
            </button>
            <span>|</span>
            <button
              disabled={!display.showLogin}
              className="p-4"
              onClick={() => setDisplay({ showLogin: false })}
              style={
                display.showLogin
                  ? { color: 'blue' }
                  : { color: 'black', opacity: 1 }
              }
            >
              Register
            </button>
          </div>
          <LoginForm display={display.showLogin} />
          <RegistrationForm display={!display.showLogin} />
          <hr />
          <SocialLogin />
        </div>
      </main>
    </>
  )
}

export default Home
